version: "3.3"

services:
  server:
    image: server:latest
    restart: always
    build:
      context: ./server
    depends_on:
      - db
    environment:
      MONGO_CONNECTION_STRING: mongodb://db:27017

  db:
    restart: always
    image: "mongo"

  client:
    image: client:latest
    build:
      context: ./client
    depends_on:
      - server
    ports:
      - "3000:3000"
    environment:
      BASE_URL: http://server:8080
